services:
    Systemin\SyliusGoogleMerchantCenter\Generator\ProductFeedGenerator:
        arguments:
            $productRepository: '@sylius.repository.product'
            $router: '@router'
    
    Systemin\SyliusGoogleMerchantCenter\Controller\ProductFeedController:
        arguments:
            $productFeedGenerator: '@Systemin\SyliusGoogleMerchantCenter\Generator\ProductFeedGenerator'
    
    Systemin\SyliusGoogleMerchantCenter\Command\GenerateProductFeedCommand:
        arguments:
            $productFeedGenerator: '@Systemin\SyliusGoogleMerchantCenter\Generator\ProductFeedGenerator'
        tags:
            - { name: 'console.command' }
