services:
    LilianBellini\SyliusGoogleMerchantCenter\Generator\ProductFeedGenerator:
        arguments:
            $productRepository: '@sylius.repository.product'
            $router: '@router'
            $url: '%env(APP_SCHEME)%://%env(APP_HOST)%'  # Injection du paramètre app.url
    
    LilianBellini\SyliusGoogleMerchantCenter\Controller\ProductFeedController:
        arguments:
            $productFeedGenerator: '@LilianBellini\SyliusGoogleMerchantCenter\Generator\ProductFeedGenerator'
    
    LilianBellini\SyliusGoogleMerchantCenter\Command\GenerateProductFeedCommand:
        arguments:
            $productFeedGenerator: '@LilianBellini\SyliusGoogleMerchantCenter\Generator\ProductFeedGenerator'
        tags:
            - { name: 'console.command' }
